Update documentation with new tutorial about working with misaligned data
etna-team/etna pull request #288
Opened 2024-03-27 09:58 UTC by d-a-bunin

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/etna-team/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/etna-team/etna/blob/master/CHANGELOG.md)?

## Proposed Changes
Look #277.

## Closing issues
Closes #277.

2024-03-28 10:17 UTC, alex-hse-repository requested changes

2024-03-28 11:07 UTC, d-a-bunin commented on docs/source/glossary.rst
>     Time series
I tried to order them by their meaning.

2024-03-28 11:12 UTC, d-a-bunin commented on docs/source/glossary.rst
> +      See :doc:`tutorials/303-hierarchical_pipeline`.
That is all I was able to find with search.

2024-03-28 11:15 UTC, d-a-bunin commented
<p>These external timestamps are sitting inside <code>df_exog</code>, they are limmited by the size of <code>df_exog</code>. If we want to extend them into infinity we need a different logic.  </p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846798'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-28 11:22 UTC, d-a-bunin commented
<p>You are forecasting the values with integer index, original index is just a feature.</p><p>If you have this feature in your forecast you know which value correspond to which timestamp.</p><p>If you don't have this feature in your forecast you could use make_timestamp_df_from_alignment to recreate it, I think. I haven't really thought about this problem. Do you have any ideas how should it work for the user?</p><p> </p><p>No, currently we can't draw forecasts with original timestamps.</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846896'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-28 11:25 UTC, d-a-bunin commented
<ul><li>aligned + regular: support natively</li><li>aligned + irregular: support* using int index + external timestamp, but we don't have any guarantees that it will work fine</li><li>misaligned + regular: support using int index + external timestamp</li><li>misaligned + irregular: support* using int index + external timestamp, but we don't have any guarantees that it will work fine</li></ul><p> </p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846733'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-28 11:26 UTC, d-a-bunin commented
<p>I don't really get what do you mean under inference strategies here, can you elaborate?</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846714'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 05:50 UTC, alex-hse-repository commented
<p>For example we can fit the pipeline on misaligned data and run inference on aligned dataset</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846714'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 05:51 UTC, alex-hse-repository commented
<p>Is it helpful info, how do you think?</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846733'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 05:54 UTC, alex-hse-repository commented
<p>Looks like parameter which I always set to 100000</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846798'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 05:57 UTC, alex-hse-repository commented
<ol><li>I don't know the use case of forecasts with misaligned data, I thought we did this track to handle cases where we wan to train on misaligned data and forecast on aligned data</li><li>May be we can add such functionality(about plotting forecasts) -- but not sure, see (1)</li></ol>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846896'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 06:02 UTC, alex-hse-repository requested changes
See comments

2024-03-29 07:25 UTC, d-a-bunin commented
<p>It doesn't work that simple. Working with misaligned data is implemented by working with integer timestamp, that's all.</p><p> </p><p>You can fit on data with integer timestamp where some segments are misaligned to others (e.g. they are really old) and later make an inference on subset of segments that you want to forecast.</p><p> </p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846714'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 07:25 UTC, d-a-bunin commented
<p>If you have a lot of memory you are free to go)</p><p> </p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846798'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 07:28 UTC, d-a-bunin commented
<p>Let's assume we have a data there some segments are really old and doesn't have to be forecasted anymore. We can align them with new segments and fit our pipeline. After that we can use that pipeline to forecast only recent segments that we are working with.</p><p>In that scenario we were able to use the patterns that we learnt from old segments.</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846896'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-29 08:54 UTC, alex-hse-repository commented
<p>Let's add example for this scenario "pipeline on misaligned data and run inference on aligned dataset"</p>

---

 <a href='https://app.reviewnb.com/etna-team/etna/pull/288/discussion/#comment-2024846714'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-03-30 06:49 UTC, alex-hse-repository approved these changes

2024-04-01 09:19 UTC, merged