Issue 468
etna-team/etna pull request #470
Opened 2024-09-04 08:32 UTC by fuglaeff

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/etna-team/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/etna-team/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

`closes #468`

2024-09-04 08:35 UTC, fuglaeff commented
I looked at the project code and it seems that these are the only weak points.

2024-09-04 11:34 UTC, d-a-bunin requested changes

2024-09-04 11:34 UTC, d-a-bunin commented on CHANGELOG.md
> +- Fix `backtest` and `forecast` commands converts `segment` to integer ([#468](https://github.com/etna-team/etna/issues/468))
Here we should add link to PR, not to issue.

2024-09-04 11:34 UTC, d-a-bunin commented on etna/commands/backtest_command.py
> +    df_timeseries = pd.read_csv(target_path, parse_dates=parse_dates, dtype={"segment": str})
We should probably add some test that checks this behavior. Smth like en example in the issue.

2024-09-04 11:34 UTC, d-a-bunin commented on etna/commands/forecast_command.py
> +    df_timeseries = pd.read_csv(target_path, parse_dates=parse_dates, dtype={"segment": str})
We should probably add some test that checks this behavior. Smth like en example in the issue.

2024-09-04 16:14 UTC, d-a-bunin commented on CHANGELOG.md
> +- Fix `backtest` and `forecast` commands converts `segment` to integer ([#470](https://github.com/etna-team/etna/pull/470))
May be it is better to rewrite to: 
```
Convert `segment` to string during reading csv in `backtest` and `forecast` commands
```

2024-09-04 20:56 UTC, fuglaeff commented
Looked at my mistakes in the tests and fixed them

2024-09-05 06:54 UTC, d-a-bunin approved these changes

2024-09-05 10:49 UTC, d-a-bunin approved these changes

2024-09-05 10:49 UTC, merged