Update `Sign`, `WAPE`, `MaxDeviation` to handle missing values
etna-team/etna pull request #530
Opened 2024-12-16 15:12 UTC by d-a-bunin

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/etna-team/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/etna-team/etna/blob/master/CHANGELOG.md)?

## Proposed Changes
See #525.

## Closing issues
Closes #525

2024-12-17 13:25 UTC, brsnw250 requested changes

2024-12-17 13:25 UTC, brsnw250 commented on etna/metrics/functional_metrics.py
> +    denominator = np.nansum(np.abs(y_true_array + nans_mask), axis=axis)
```suggestion
    denominator = np.nansum(np.abs(y_true_array * np.isnan(y_pred_array)), axis=axis)
```

2024-12-17 13:25 UTC, brsnw250 commented on etna/metrics/functional_metrics.py
> +    numerator = np.nansum(np.abs(y_true_array - y_pred_array), axis=axis)
According to the documentation for versions of numpy > 1.9 `nansum` will return 0 for all empty array.  We should set it to `NaN` in such scenarios.
Seems like we don't have a test case when this behavior shows up (numerator computed from a full empty array and denominator has values).

2024-12-17 14:22 UTC, d-a-bunin commented on tests/test_metrics/test_functional_metrics.py
> +        # (np.array([1.0, 2.0, 3.0]), np.array([3.0, 1.0, 2.0]), "joint", 2.0),
Yes, will be fixed.

2024-12-17 14:25 UTC, d-a-bunin commented on etna/metrics/functional_metrics.py
> +    isnan = np.all(np.isnan(y_pred_array - y_true_array), axis=axis)
I think that this optimization isn't significant. I'll try to add it in the next commit.

2024-12-18 08:19 UTC, brsnw250 approved these changes

2024-12-18 08:22 UTC, merged