Create EventTransform
etna-team/etna pull request #78
Opened 2023-09-07 19:49 UTC by egoriyaa

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/etna-team/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/etna-team/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues
closes #14

2023-09-08 04:36 UTC, egoriyaa commented on etna/transforms/timestamp/event.py
> +        out_column:
may be it is better to get in_column value default?

2023-09-08 05:27 UTC, alex-hse-repository requested changes

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        mode: {'binary', 'distance'}, default='binary'
There should be typing in docs
<img width="436" alt="Снимок экрана 2023-09-08 в 08 00 20" src="https://github.com/etna-team/etna/assets/55380696/40401346-8548-4aeb-afa0-13a1eea9fba9">

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        mode: {'binary', 'distance'}, default='binary'
Better to create `Enum` for this parameter like [here](https://github.com/etna-team/etna/blob/3489d1de4dfad861a4f64c8e0a9aa2f48ed76da3/etna/transforms/missing_values/imputation.py#L51)

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        if not isinstance(n_pre, int) or not isinstance(n_post, int):
You don't need to check it explicitly, we add typing for such purpose -- in the perfect world each argument in each constructor should be validated like this but for this purpose better to use sth like [pydantic](https://github.com/pydantic/pydantic)

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        if not isinstance(n_pre, int) or not isinstance(n_post, int):
We should do it everywhere or don't do it at all

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +    def _params_to_tune(self) -> Dict[str, BaseDistribution]:
Why it private? The original method is public [see](https://github.com/etna-team/etna/blob/3489d1de4dfad861a4f64c8e0a9aa2f48ed76da3/etna/transforms/base.py#L167)

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        prev = prev * indexes
Better to define `prev=indexes.copy()` to avoid this operation

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        if self.mode == 'binary':
Here it is better to create variable like this
```
distance = 1 if self.mode == 'binary' else 1/prev
```
This way you will avoid code duplication below

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        if self.mode == 'binary':
Also check what happens if some values of prev are zero(not really matters here I guess)

2023-09-08 05:27 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +        post = df.copy()
Try to create the separate method to cover this logic, it is mostly the same for prev and post -- try to avoid code duplication

2023-09-12 05:15 UTC, alex-hse-repository requested changes

2023-09-12 05:15 UTC, alex-hse-repository commented on tests/test_transforms/test_timestamp/test_event_transform.py
> +def test_fit_transform(ts_check_event_transform: TSDataset, ts_check_event_transform_expected: TSDataset):
Try to rework this test, it should be parametrized with
- mode
- n_pre
- n_post

2023-09-12 05:15 UTC, alex-hse-repository commented on tests/test_transforms/test_timestamp/test_event_transform.py
> +    dataframes = [pd.DataFrame({"timestamp": pd.date_range("2020-01-01", periods=periods)}) for _ in range(3)]
May you create dataframes in more explicit way:
```
df = generate_ar_df() -- don't need special targets
df_exog = generate_ar_df().rename(target -> holiday)
df_exog["holiday"] = [0, 1, 0, 1, 1, 0, 0, 0, 1, 0] + [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] + [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```

2023-09-12 05:15 UTC, alex-hse-repository commented on tests/test_transforms/test_timestamp/test_event_transform.py
> +            df["holiday"] = np.array([0, 1, 0, 1, 1, 0, 0, 0, 1, 0])
As I said exog variables should be in separate dataframe and should be passed into `df_exog` parameter

2023-09-12 05:15 UTC, alex-hse-repository commented on tests/test_transforms/test_timestamp/test_event_transform.py
> +def ts_check_event_transform_expected() -> TSDataset:
You can create fixture out of another fixture like
```
def ts_check_event_transform_expected(ts_check_event_transform)
```
And just add the answers

2023-09-12 05:15 UTC, alex-hse-repository commented on tests/test_transforms/test_inference/conftest.py
> +def ts_with_binary_exoc(random_seed) -> TSDataset:
Try to use methods from `datasets.datasets_generation.py` for this purpose or create global fixture with binary column, which you will also use un tests for EventTransform

2023-09-12 05:15 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +            col = col.bfill().fillna(indexes)
I fact you can rewrite it this way:
```
col = (col.bfill() if column == "prev" else col.ffill()).fillna(indexes)
col = (col - indexes).abs()
```

2023-09-13 13:01 UTC, alex-hse-repository requested changes

2023-09-13 13:01 UTC, alex-hse-repository commented on tests/test_transforms/test_timestamp/test_event_transform.py
> +    event = EventTransform(in_column="holiday", out_column="holiday", n_pre=1, n_post=1)
Here and in the next test better to remove "holiday" column from the dataset via `FilterTransform` to make sure that model works with generated features

2023-09-13 13:01 UTC, alex-hse-repository commented on tests/test_transforms/test_timestamp/test_event_transform.py
> +    event = EventTransform(in_column="holiday", out_column="holiday", n_pre=1, n_post=1)
May be you can also add some test cases via parametrization

2023-09-13 13:58 UTC, egoriyaa commented on etna/transforms/timestamp/event.py
> +    >>> ts_copy = deepcopy(tsds)
ts is used in this example
ts_copy is used in example below

2023-09-13 15:38 UTC, egoriyaa commented on tests/conftest.py
> +    df_exog = generate_const_df(start_time="2020-01-01", periods=periods_exog, freq="D", scale=1, n_segments=3)
this fixture is used only to check pipeline, backtest and in inference tests. they don't depend on values

2023-09-14 12:10 UTC, alex-hse-repository commented on tests/conftest.py
> +    df_exog = generate_const_df(start_time="2020-01-01", periods=periods_exog, freq="D", scale=1, n_segments=3)
It should contain data from general case, we can miss some unexpected behavior

2023-09-14 12:12 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +    >>> ts_copy = deepcopy(tsds)
You can do sth like this:
```
transform.fit_transform(deepcopy(ts))
transform.fit_transform(deepcopy(ts))
```

2023-09-15 08:01 UTC, alex-hse-repository commented on etna/transforms/timestamp/event.py
> +    >>> transform = EventTransform(in_column='holiday', out_column='holiday', n_pre=2, n_post=2)
May be it is better to place here example with `mode = "distance"`

2023-09-15 11:04 UTC, alex-hse-repository approved these changes

2023-09-15 11:04 UTC, merged